export const actionTypes = {
    STEP_ACTIVE: "STEP_ACTIVE",
    ADD_SUB_TIPO_TRAMITE_DATA: "ADD_SUB_TIPO_TRAMITE_DATA",
    DELETE_SUB_TIPO_TRAMITE_DATA: "DELETE_SUB_TIPO_TRAMITE_DATA",
    SELECTED_SUB_TIPO_TRAMITE: "SELECTED_SUB_TIPO_TRAMITE",
    CHANGUE_FECHA_HORA_TURNO: "CHANGUE_FECHA_HORA_TURNO",
    MODALIDAD_ACLARACION: "MODALIDAD_ACLARACION",
    ADD_USER: "ADD_USER",
    DELETE_MODALIDAD_ACLARACION: "DELETE_MODALIDAD_ACLARACION",
    DELETE_FECHA_HORA_TURNO: "DELETE_FECHA_HORA_TURNO",
    DELETE_USER: "DELETE_USER"
}